<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php
        foreach($cssOn as $css){
            echo('<link rel="stylesheet" href="'.$css.'">');
        }
    ?>
    <title>Mon Super Blog</title>
</head>
<body>
<section class="container">
        <nav>
            <div class="logo">
                <a href="index.php">
                    <img src="./img/logo.png" alt="">
                    <p>Mon Super Blog</p>
                </a>
            </div>

            <div class="menu">
                <form action="" method="post">
                    <label for="inpL">Login : </label>
                    <input type="text" name="inpL" id="inpL">
                    <label for="inpP">Password : </label>
                    <input type="password" name="inpP" id="inpP">
                    <button type="submit">sign in</button>
                </form>
            </div>

            <div class="create">
                <a href="create.php">
                    <p>créer un compte</p>
                </a>
            </div>
        </nav>